kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: ci
      labels:
        app: prow
        component: repo-init-api
      name: repo-init-api
    spec:
      ports:
        - name: main
          port: 80
          protocol: TCP
          targetPort: main
        - name: metrics
          port: 9090
          protocol: TCP
          targetPort: metrics
      selector:
        app: prow
        component: repo-init-api
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: prow
        component: repo-init-api
      name: repo-init-api
      namespace: ci
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      port:
        targetPort: main
      to:
        kind: Service
        name: repo-init-api
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: repo-init-api
      namespace: prow-monitoring
      labels:
        app: prow
        component: repo-init-api
        prow-app: repo-init-api
    spec:
      endpoints:
        - interval: 30s
          port: metrics
          scheme: http
      namespaceSelector:
        matchNames:
          - ci
      selector:
        matchLabels:
          app: prow
          component: repo-init-api
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      namespace: ci
      name: repo-init-api
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"repo-init:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"repo-init-api\")].image"}]'
    spec:
      replicas: 2
      strategy:
        type: RollingUpdate
      selector:
        matchLabels:
          app: prow
          component: repo-init-api
      template:
        metadata:
          labels:
            app: prow
            component: repo-init-api
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: component
                          operator: In
                          values:
                            - repo-init-api
                    topologyKey: "kubernetes.io/hostname"
          containers:
            - name: repo-init-api
              image: repo-init:latest
              args:
                - -loglevel=info
                - -mode=api
                - -port=8080
                - -github-token-path=/etc/github/oauth
                - -github-endpoint=httpp://ghproxy
                - -num-repos=4
                - -server-config-path=/etc/repo-init-config
              ports:
                - name: main
                  containerPort: 8080
                - name: metrics
                  containerPort: 9090
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8081
                initialDelaySeconds: 3
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /healthz/ready
                  port: 8081
                initialDelaySeconds: 10
                periodSeconds: 3
                timeoutSeconds: 600
              resources:
                requests:
                  memory: "3Gi"
                  cpu: "500m"
              volumeMounts:
                - mountPath: /etc/github
                  name: token
                  readOnly: true
                - mountPath: /etc/repo-init-config
                  name: repo-init-config
                  readOnly: true
          volumes:
            - name: token
              secret:
                secretName: github-credentials-openshift-bot
            - name: repo-init-config
              projected:
                sources:
                  - secret:
                      name: repo-init
                      items:
                        - key: github-client-secret
                          path: github-client-secret
                  - configMap:
                      name: repo-init-config
