kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    namespace: ci
    labels:
      app: prow
      component: repo-init-ui
    name: repo-init-ui
  spec:
    ports:
    - name: main
      port: 80
      protocol: TCP
      targetPort: main
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
    selector:
      app: prow
      component: repo-init-ui
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: prow
      component: repo-init-ui
    name: repo-init-ui
    namespace: ci
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    port:
      targetPort: main
    to:
      kind: Service
      name: repo-init-ui
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: repo-init-ui
    namespace: prow-monitoring
    labels:
      app: prow
      component: repo-init-ui
      prow-app: repo-init-ui
  spec:
    endpoints:
    - interval: 30s
      port: metrics
      scheme: http
    namespaceSelector:
      matchNames:
      - ci
    selector:
      matchLabels:
        app: prow
        component: repo-init-ui
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: ci
    name: repo-init-ui
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"repo-init:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"repo-init-ui\")].image"}]'
  spec:
    replicas: 2
    strategy:
      type: RollingUpdate
    selector:
      matchLabels:
        app: prow
        component: repo-init-ui
    template:
      metadata:
        labels:
          app: prow
          component: repo-init-ui
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - repo-init-ui
                topologyKey: "kubernetes.io/hostname"
        containers:
        - name: repo-init-ui
          image: repo-init:latest
          args:
          - --loglevel=info
          - --mode=ui
          - --port=8080
          ports:
          - name: main
            containerPort: 8080
          - name: metrics
            containerPort: 9090
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 600
          resources:
            requests:
              memory: "3Gi"
              cpu: "500m"
          volumeMounts:
          - name: rect-config
            mountPath: "/usr/bin"
            subPath: ".env"
            readOnly: true
        volumes:
        - name: react-config
          projected:
            sources:
            - secret:
                name: repo-init
                items:
                  - key: client-id
                    path: REACT_APP_CLIENT_ID
