base_images:
  image1:
    name: image1
    namespace: ns
    tag: tag
binary_build_commands: go build ./cmd/...
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
canonical_go_repository: k8s.io/cool-repo
operator:
  bundles:
  - as: ci-index
    context_dir: ./context-dir
    dockerfile_path: ./Dockerfile.bundle
  substitutions:
  - pullspec: registry.io/thisimage:4.1
    with: image1
releases:
  latest:
    release:
      architecture: amd64
      channel: stable
      version: "4.10"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: go test -c ./test/...
tests:
- as: unit-test
  commands: make unit
  container:
    from: src
- as: e2e-operator
  steps:
    dependencies:
      OO_INDEX: ci-index
    env:
      OO_CHANNEL: "4.3"
      OO_INSTALL_NAMESPACE: '!create'
      OO_PACKAGE: bundle-package
      OO_TARGET_NAMESPACES: '!install'
    test:
    - as: e2e-operator
      commands: make operator
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: optional-operators-ci-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: apitest
